[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "23-day1"
path = "src/23/day1/main.rs"

[[bin]]
name = "23-day2"
path = "src/23/day2/main.rs"

[dependencies]
